### ISSUE TITLE
[Bug]: Error: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by abriginets** [jmcdo29/ogma#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have an endpoint in my NestJS application that responds with image instead of json:
```ts
@Get('/og/:hash')
async getOpenGraphImage(@Param('hash') hash: string, @Res() response: Response): Promise<Response<Buffer>> {
  const imageBuffer = await this.ogImageService.getImageBuffer(hash);

  return response.setHeader('Content-Type', 'image/png').send(imageBuffer);
}
```
But whenever I try to hit this endpoint I see the following error in the terminal:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at ServerResponse.header (/home/goodwin/flaut-nestjs/node_modules/express/lib/response.js:776:10)
    at ServerResponse.send (/home/goodwin/flaut-nestjs/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/goodwin/flaut-nestjs/node_modules/express/lib/response.js:267:15)
    at ExpressAdapter.reply (/home/goodwin/flaut-nestjs/node_modules/@nestjs/platform-express/adapters/express-adapter.js:36:57)
    at ExceptionsHandler.handleUnknownError (/home/goodwin/flaut-nestjs/node_modules/@nestjs/core/exceptions/base-exception-filter.js:38:24)
    at ExceptionsHandler.catch (/home/goodwin/flaut-nestjs/node_modules/@nestjs/core/exceptions/base-exception-filter.js:17:25)
    at ExceptionsHandler.next (/home/goodwin/flaut-nestjs/node_modules/@nestjs/core/exceptions/exceptions-handler.js:16:20)
    at /home/goodwin/flaut-nestjs/node_modules/@nestjs/core/router/router-proxy.js:13:35
```

### Minimum reproduction code

Private repo with copyrighted codebase

### Expected behavior

Ogma should verify if the response has already been sent by checking out the value of `res.headersSent`

### Package(s) version

- `@ogma/nestjs-module`: 3.1.1
- `@ogma/platform-express`: 3.0.1

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
The entirety of that error seems to come from nest, not from ogma. Strange either way, as `@Res()` should make nest not run post-controller interceptor logic or try to send any response. I'm gonna need a reproduction to see what's happened

**Comment by abriginets** [comment]
@jmcdo29 I've checked that. NestJS without ogma logger shows no error.

**Comment by jmcdo29** [comment]
Then can you get me a reproduction so I can see what's happening here?

**Comment by abriginets** [comment]
There you go. https://github.com/abriginets/ogma-nestjs-headers-sent
Just clone it, `npm i && npm run start:dev` and hit http://localhost:3333. You'll be able to see the error in the terminal. Also I mentioned that this issue completely blocks any other incoming requests to Nest after the faulty request was performed. All the requests are returning with ECONNREFUSED after that.

**Comment by jmcdo29** [comment]
Thank you so much for the reproduction. I was able to track this down, it's actually not specific to Ogma, but to something Nest is doing that it shouldn't be. What's happening is that Ogma ends up calling `JSON.stringify(data)` inside the interceptor's post-controller logic. This is to normally try and figure out how large the response body is. When doing this on the response object (which you're returning) it seems some headers try to get set. 

Normally I'd expect Nest not to continue with the interceptor if `@Res()` is used. A simple reproduction of the error can be made with an interceptor like 

```ts
@Injectable()
class DummyInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler) {
    return next.handle().pipe(tap((data) => console.log(JSON.stringify(data))));
  }
}
```

I'll open an issue with the Nest repo about the error. In the meantime, to get around this you can do
```ts
res.setHeaders().send()
return
```
Just so you aren't returning the response object.

**Comment by abriginets** [comment]
So what you're saying is that API endpoints which making use of `@Res` shouldn't support any request interceptors by design thus ogma won't be able to log any interaction with those endpoints, am I right?

**Comment by jmcdo29** [comment]
Correct. That's the way that Nest states it should be in the docs

> Also, in the example above, you lose compatibility with Nest features that depend on Nest standard response handling, such as Interceptors and `@HttpCode()` / `@Header()` decorators. To fix this, you can set the passthrough option to true, as follows:

- [from here](https://docs.nestjs.com/controllers#library-specific-approach)

For your approach, as you need to send a file in response, you could use a [StreamableFile](https://docs.nestjs.com/techniques/streaming-files) and keep the ability to use interceptors so you can still get these logs

**Comment by abriginets** [comment]
Oh, I didn't mention in the docs that `StreamableFile` can accept not only a stream but also a buffer. I was able to achieve full compatibility with Ogma for both simple and more complex endpoints:
```ts
@Get('/location/code/:code/width/:width/height/:height/extension/:extension')
@Header('Content-Disposition', 'inline')
async getLocationImage(
  @Param('code') code: string,
  @Param('width', new ParseIntPipe()) width: number,
  @Param('height', new ParseIntPipe()) height: number,
  @Param('extension', new LocationImageExtensionValidationPipe()) extension: LocationImageFormatEnum,
  @Res({ passthrough: true }) response: Response,
): Promise<StreamableFile> {
  const imageBuffer = await this.imageLocationService.getLocationImage(code, width, height, extension);

  response.setHeader('Content-Type', mime.contentType(extension) as string);

  return new StreamableFile(imageBuffer);
}

@Get('/og/:hash')
@Header('Content-Disposition', 'inline')
@Header('Content-Type', 'image/png')
async getOpenGraphImage(@Param('hash') hash: string): Promise<StreamableFile> {
  const imageBuffer = await this.ogImageService.getImageBuffer(hash);

  return new StreamableFile(imageBuffer);
}
```
To summarize:
- `@Header('Content-Type', 'image/png')` decorator can be used to set image format declarative way
- To set image type imperatively `response.setHeader('Content-Type', imageFormat);` notation can be used for cases when image format depends on request parameters, but `@Res` decorator must be used with `passthrough` option set to `true`.
- Also I'm using `@Header('Content-Disposition', 'inline')` to disable "download the file" behavior in the browser because Nest appends `Content-Disposition: null` header by default when `StreamableFile` is returned.

All of the above helped me to achieve the absolute same behavior decleratively compared to what I had before imperatively. Thank you!

**Comment by jmcdo29** [comment]
You can also pass a second parameter to the `StreamableFile`'s constructor for setting content dispositions and such. Glad you were able to make it work. I'll go ahead and close out the issue, as it's something at Nest's level, but I'll keep an eye on this if you need anything else
