### ISSUE TITLE
[Logger]: File log rotation

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [jmcdo29/ogma#1119]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Missing log rotation option.

### Describe the solution you'd like

It would be great if there would be a configurable log rotation option for saving to file system

### What is the motivation / use case for changing the behavior?

keeping track of logs from different days or size

**Comment by jmcdo29** [comment]
Ogma was written to be very open and plug-n-playable with any stream you like. You can use something like [rotating-file-stream](https://github.com/iccicci/rotating-file-stream) as the stream and it'll work for you :smile:

**Comment by jmcdo29** [comment]
By default, ogma writes out to `process.stdout`. If you're writing to a file, the logic to rotate between files falls to the developer. It's my opinion that the logger should be in charge of writing the logs, but the destination should fall to configuration so that it's not locked in

**Comment by sschneider-ihre-pvs** [comment]
great suggestion with roating file stream 👍

**Comment by IgnisDa** [comment]
@sschneider-ihre-pvs Were you able to get this working with rotating-file-stream? If so can you share the code. I would like to integrate into my own project.

**Comment by sschneider-ihre-pvs** [comment]
I have not.
