### ISSUE TITLE
[Bug]: ogma cli not working on linux

### ISSUE THREAD

**Issue by Nightbr** [jmcdo29/ogma#1172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hey,
thanks for this awesome logger, really fell in love with it!

I'm on Linux and would like to use the ogma CLI but the shebang interpreter is not the usual for Linux:

`#! /bin/node` should be `#!/usr/bin/env node`

You can also refer to this: https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang

### Minimum reproduction code

NaN

### Steps to reproduce

1. `npm install -g @ogma/cli`
2. `ogma test.log`

### Expected behavior

Be able to run ogma cli on Linux.

### Package(s) version

- `@ogma/cli`: 2.1.5

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Thanks in advance, and don't hesitate if you need more debug or help!

Cheers

**Comment by jmcdo29** [comment]
Interesting. I dev on Linux, but use zsh as a shell. Feel free to make a PR to fix it. If you do, please add a changeset too
