### ISSUE TITLE
[Bug]: property in "masks" are are required in the response in other case application crash

### ISSUE THREAD

**Issue by ryakoviv** [jmcdo29/ogma#1678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when you provide property in "masks" array and that property is not presented in the response you get error 
TypeError: Cannot read properties of undefined (reading 'toString')\n    at OrderResponseDataDto.<anonymous> (/usr/src/app/node_modules/@ogma/logger/src/logger/ogma.js:100:41)\n    at JSON.stringify (<anonymous>)\n    at Ogma.formatJSON (/usr/src/app/node_modules/@ogma/logger/src/logger/ogma.js:145:21)\n    at Ogma.printMessage (/usr/src/app/node_modules/@ogma/logger/src/logger/ogma.js:73:30)\n    at Ogma.info (/usr/src/app/node_modules/@ogma/logger/src/logger/ogma.js:217:14)\n    at OgmaService.printMessage (/usr/src/app/node_modules/@ogma/nestjs-module/src/ogma.service.js:162:31)\n    at OgmaService.info (/usr/src/app/node_modules/@ogma/nestjs-module/src/ogma.service.js:53:14)\n    at OgmaInterceptor.log (/usr/src/app/node_modules/@ogma/nestjs-module/src/interceptor/ogma.interceptor.js:92:22)\n    at OgmaInterceptor.shouldLogAndDoIt (/usr/src/app/node_modules/@ogma/nestjs-module/src/interceptor/ogma.interceptor.js:61:22)\n    at Object.next (/usr/src/app/node_modules/@ogma/nestjs-module/src/interceptor/ogma.interceptor.js:47:22)","time":"2023-05-22T11:55:11.451Z"}

### Minimum reproduction code

don't have it

### Steps to reproduce

1. put in "masks" some property
2. provide that property in response as undefined

### Expected behavior

when you provide property in "masks" array and that property is not presented in the response your application should not crash)

### Package(s) version

@ogma/nestjs-module: 4.2.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by ryakoviv** [comment]
value can be undefined here
https://github.com/jmcdo29/ogma/blob/main/packages/logger/src/logger/ogma.ts#L110

**Comment by ryakoviv** [comment]
https://github.com/jmcdo29/ogma/pull/1679

**Comment by jmcdo29** [comment]
Fixed in @ogma/logger@3.1.6
