### ISSUE TITLE
[Bug]: the async configuration example given in nestjs-module emits an error

### ISSUE THREAD

**Issue by opensas** [jmcdo29/ogma#215]
## Current behavior

The following [sample code](https://github.com/jmcdo29/ogma/tree/master/packages/nestjs-module#asynchronous-configuration)

```typescript
@Module({
  imports: [
    OgmaModule.forRootAsync({
      useFactory: (config: ConfigService) => ({
        service: {
          json: config.isProd(),
          stream: {
            write: (message) =>
              appendFile(config.getLogFile(), message, (err) => {
                if (err) {
                  throw err;
                }
              })
          },
          application: config.getAppName()
        },
        interceptor: {
          http: ExpressParser,
          ws: false,
          gql: false,
          rpc: false
        }
      }),
      inject: [ConfigService]
    })
  ]
})
```

Throws the following error:

- write(message) should return a boolean

## Expected behavior

The example should work flawlessly

## Possible Solution

To fix the errors I had to do the following:

```typescript
@Module({
  imports: [
    OgmaModule.forRootAsync({
      useFactory: (config: ConfigService) => ({
        service: {
          json: config.isProd(),
          stream: {
            write: (message: string): boolean => {
              appendFile(config.getLogFile(), message, (err) => {
                if (err) {
                  throw err;
                }
              })
              return true
            }
          },
          application: config.getAppName()
        },
        interceptor: {
          http: ExpressParser,
          ws: false,
          gql: false,
          rpc: false
        }
      }),
      inject: [ConfigService]
    })
  ]
})
```

## Environment

<pre><code>
@ogma/nestjs-module": "^0.3.0"
@ogma/platform-express": "^0.3.0

For Tooling issues:
- Node version: v12.11.1
- Platform:  Linux xps 5.0.0-1068-oem-osp1 #73-Ubuntu

Others:
using npm
</code></pre>

**Comment by jmcdo29** [comment]
Currently, the `stream` option is an union of `NodeJS.WriteStream` and `NodeJS.WriteableStream` that must have the property `write` from `NodeJS.WriteableStream`. [According to NodeJS's docs](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback), `write` returns a boolean, which is where this is coming from. 

With that said, it may be a better idea to make this a custom interface that can be written as `void`, like so
```ts
export interface OgmaStream {
  write: (message) => void,
  hasColors?: () => boolean
}
```
And have a default for `hasColors` resulting in `true` instead of relying on information from the stream itself. 

Shouldn't be too hard of a change, would you like to tackle it in a PR?

**Comment by jmcdo29** [comment]
Added to v0.4.0. This will most likely be the last pre v1 version. Thanks for the idea

**Comment by kuncevic** [comment]
In my case I have some other errors using Async Config:

`useFactory` types mismatch 

```
TS2322: Type
(config: ConfigService<Record<string, unknown>, false>) => {   service: {     json: any;     stream: {       write: (message: any) => void;     };     application: any;   };   interceptor: {     http: typeof ExpressParser;     ws: boolean;     gql: boolean;     rpc: boolean;   }; }/

is not assignable to type

(...args: any[]) => OgmaModuleOptions | Promise<OgmaModuleOptions>
```

as well ass everything `config.prop()` does not exist, e.g `TS2339: Property isProd does not exist on type ConfigService<Record<string, unknown>, false`

I've pretty match copy-pasted the code additionally had to install @nestjs/config. 

any ideas?

**Comment by kuncevic** [comment]
@jmcdo29  In my case I have some other errors using Async Config:

`useFactory` types mismatch 

```
TS2322: Type
(config: ConfigService<Record<string, unknown>, false>) => {   service: {     json: any;     stream: {       write: (message: any) => void;     };     application: any;   };   interceptor: {     http: typeof ExpressParser;     ws: boolean;     gql: boolean;     rpc: boolean;   }; }/

is not assignable to type

(...args: any[]) => OgmaModuleOptions | Promise<OgmaModuleOptions>
```

as well ass everything `config.prop()` does not exist, e.g `TS2339: Property isProd does not exist on type ConfigService<Record<string, unknown>, false`

I've pretty match copy-pasted the code additionally had to install @nestjs/config. 

any ideas?
