### ISSUE TITLE
[Bug]: GraphQL subscriptions vs Ogma Interceptor

### ISSUE THREAD

**Issue by roderik** [jmcdo29/ogma#463]
## Bug Report

I've been using Ogma for a while now, and today decided to add GraphQL subscriptions. 

## Current behavior

As far as I can tell, the Ogma interceptor chooses platform-express for this request and then dies because request is not defined. 

```
[TypeError: Cannot set property 'requestId' of undefined
    at GraphQLParser.setRequestId (/Users/roderik/Development/bpaas-launchpad/packages/module-strict-config/node_modules/@ogma/platform-express/lib/express-interceptor.service.js:32:23)
    at DelegatorService.setRequestId (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/@ogma/nestjs-module/lib/interceptor/providers/delegator.service.js:27:22)
    at OgmaInterceptor.intercept (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/@ogma/nestjs-module/lib/interceptor/ogma.interceptor.js:37:23)
    at /Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
    at InterceptorsConsumer.intercept (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:25:24)
    at target (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/@nestjs/core/helpers/external-context-creator.js:76:60)
    at /Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/@nestjs/core/helpers/external-proxy.js:9:30
    at /Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/graphql/subscription/subscribe.js:177:19
    at new Promise (<anonymous>)
    at executeSubscription (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/graphql/subscription/subscribe.js:162:10)
    at /Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/graphql/subscription/subscribe.js:137:9
    at new Promise (<anonymous>)
    at createSourceEventStream (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/graphql/subscription/subscribe.js:130:10)
    at subscribeImpl (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/graphql/subscription/subscribe.js:69:23)
    at subscribe (/Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/graphql/subscription/subscribe.js:32:65)
    at /Users/roderik/Development/bpaas-launchpad/packages/launchpad-api/node_modules/subscriptions-transport-ws/src/server.ts:359:52]
```

## Input Code

```ts
    return {
      service: {
        logLevel: this.isTestRun() ? 'ERROR' : 'ALL',
        color: true,
        application: this.get<Environments>('environment'),
        json: this.runsOnHeroku(),
      },
      interceptor: {
        http: ExpressParser,
        ws: false,
        gql: GraphQLParser,
        rpc: false,
      },
    };
```

## Expected behavior

It should pick GraphQLParser as an interceptor

## Environment

<pre><code>
latest everything
</code></pre>

**Comment by roderik** [comment]
It is actually in the GraphQLParser where it fails.
Adding the WsParser did not help (trying out everything)

**Comment by jmcdo29** [comment]
Thanks for reporting this. In general, subscriptions don't get logged through the ogma interceptor, as generally I couldn't find the metadata to log. 

With that said, if you can provide a minimum reproduction I'll find where in the `GraphQLParser` this is happening and either silence it, or figure it where the expected metadata is and get subscriptions actually working

**Comment by roderik** [comment]
I had to disable all interceptors, it completely crashes when I send a subscription. "req" is missing in the gql context so this function cannot work. 

I also tried disabling the http express interceptor to see I that would work, but it keeps dying with the same message.


Maybe this helps:

In https://github.com/jmcdo29/ogma/blob/main/packages/nestjs-module/src/interceptor/providers/delegator.service.ts#L21 here it tries to initiate the setRequestId. It does so using a parser based on the type, and it returns the gqlParser of type GqlInterceptorService

Not notice that https://github.com/jmcdo29/ogma/blob/c4c3cc0dc22ef233eb062fd71170f852277909d0/packages/platform-graphql/src/graphql-interceptor.service.ts does not have setRequestId, but it does extend the Express one

Which is how you end here: https://github.com/jmcdo29/ogma/blob/c4c3cc0dc22ef233eb062fd71170f852277909d0/packages/platform-express/src/express-interceptor.service.ts#L30

That explains the weird stack trace where the GraphQLParser appears to be in express-interceptor.service.js

My guess, for a web socket gql subscription, https://github.com/jmcdo29/ogma/blob/c4c3cc0dc22ef233eb062fd71170f852277909d0/packages/platform-graphql/src/graphql-interceptor.service.ts#L16 does not contain the request, and in a regular call it does, which is why it works for normal requests but not here.

Maybe you need https://github.com/jmcdo29/ogma/blob/c4c3cc0dc22ef233eb062fd71170f852277909d0/packages/nestjs-module/src/interceptor/providers/websocket-interceptor.service.ts#L11 to get it?





https://github.com/jmcdo29/ogma/blob/c4c3cc0dc22ef233eb062fd71170f852277909d0/packages/platform-express/src/express-interceptor.service.ts#L30

**Comment by jmcdo29** [comment]
I'll try to get something added to my gql integration tests and see what I can do about adding subscriptions to the logs. At the very least that would stop this error from happening. I'll also try to get a fix up soon so that Ogma doesn't stop you from developing what you're working on

**Comment by roderik** [comment]
No rush, I disabled the interceptors completely, I'm good for a while

**Comment by jtag05** [comment]
@jmcdo29 I'm currently running into this exact issue.  It doesn't seem that the code changes in #473 are on the current main branch anymore or the 3.0.1 release of `@ogma/platform-graphql`

I also tested those changes by extending the `GraphQLParser` and manually adding them, but I'm still not seeing subscriptions in the logs. 

Any insight would be greatly appreciated.
