### ISSUE TITLE
[Bug]: GraphQL/HTTP request not registered

### ISSUE THREAD

**Issue by skrrriiieeet** [jmcdo29/ogma#517]
## Current behavior

After setting up the Ogma logger together with the GraphQL Parser, the request and request id is not being registered. I also tested the HTTP which is also not working.

## Input Code

```ts
    OgmaModule.forRoot({
      service: {
        color: true,
        json: false,
        application: 'Backend',
      },
      interceptor: {
        http: ExpressParser,
        ws: false,
        gql: GraphQLParser,
        rpc: false,
      },
    }),
    GraphQLModule.forRoot({
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
      playground: config.graphql.playground,
      debug: config.graphql.debug,
      // We pass in context here so we can access res in GraphQL and make redirects etc.
      context: ({ req, res }) => ({ req, res }),
      cors: {
        origin: config.security.cors,
        credentials: true,
      },
    }),
```

```ts
@Module({
  imports: [
    OgmaModule.forFeature(MyService, { addRequestId: true }),
  ],
  providers: [MyService],
})
export class MyModule{}
```

```ts
@Injectable()
export class MyService {
  constructor(
    @OgmaLoggerRequestScoped(MyService) private readonly logger: OgmaService,
  ) {}
```

![omga 4](https://user-images.githubusercontent.com/25202811/108477821-07694d80-7294-11eb-9b41-c7377ae3ee85.PNG)

## Expected behavior

I would expect the request and request id would be attached to the logging event. It seems like the GraphQl/HTTP events are not registered at all.

## Environment

<pre><code>
@ogma/nestjs-module version: 1.0.0

 
For Tooling issues:
- Node version: 14.15.4
- Platform:  Windows with Ubuntu 20.04 WSL 2.0

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Thanks for logging this! Do you have a minimum reproduction available?

**Comment by skrrriiieeet** [comment]
This should help https://github.com/jakobskytte/ogma-reproduction

**Comment by jmcdo29** [comment]
Found it! Not sure why I didn't see it before. For the request scoped logs to have a correlationId, you need to use the `OgmaInterceptor` at a global level, meaning you need to add
```ts
 providers: [
    {
      provide: APP_INTERCEPTOR,
      useClass: OgmaInterceptor,
    },
  ],
```
This will allow the interceptor to create and add a correlationId to the request.Let me know if I need to make this clearer in the docs.

**Comment by skrrriiieeet** [comment]
Perfect! Works now. Thanks. I haven't played around with Interceptors yet, so might be why I missed it. But I definitely think adding that small snippet in the docs would have made a big difference.
