### ISSUE TITLE
[Bug]: `this.logger.log(new Error())` prints empty object

### ISSUE THREAD

**Issue by jmcdo29** [jmcdo29/ogma#526]
## Current behavior

If an `Error` instance is passed to any logger method other than `printError`, the printed log is an empty object `{}`

## Input Code

```ts
const { Ogma } = require('@ogma/logger');
const ogma = new Ogma();
ogma.log(new Error('I want to see this'));
```

## Expected behavior

The logger should log the error message and error name.

## Possible Solution

Make sure, before running `typeof message === 'object'` that the message isn't an error object.

## Environment

<pre><code>
@ogma/logger version: 1.0.0
</code></pre>

**Comment by jonatasfernandespimenta** [comment]
I tried logging the error in NestJS using JSON mode false and I got this result
```js
[2021-03-17T14:01:37.358Z] [INFO]  [Macs-Mac-mini.local] [NestJS] 7346  [UserService] 
{}
```
