### ISSUE TITLE
[Parser]: Custom LogLevels

### ISSUE THREAD

**Issue by psteinroe** [jmcdo29/ogma#535]
## Feature Request
It would be great to overwrite the log levels.

## Describe the solution you'd like
A way to overwrite the log levels for printing. The methods should stay the same, just the print would change.

## Teachability, Documentation, Adoption, Migration Strategy
Example from Pino using nestjs-pino

```
return LoggerModule.forRootAsync({
    imports: [ConfigModule],
    useFactory: (configService: ConfigService<Configuration>) => {
      const severityLookup: Record<string, string> = {
        default: 'DEFAULT',
        silly: 'DEFAULT',
        verbose: 'DEBUG',
        debug: 'DEBUG',
        http: 'INFO',
        info: 'INFO',
        warn: 'WARNING',
        error: 'ERROR',
      };

      return {
        pinoHttp: {
          formatters: {
            level(label, number) {
              return { severity: severityLookup[label], level: number };
            },
          },
        },
      };
    },
    inject: [ConfigService],
  });
```

## What is the motivation / use case for changing the behavior?
Some cloud providers require certain log levels for their log collectors to pick it up properly. See [Googles log levels](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity) as an example.

**Comment by jmcdo29** [comment]
This is something I've had in mind. Generally it seems doable enough. I'll se if I can get this added in soon. I've got a good number of changes coming down on the internals, but it shouldn't be anything API affecting.

**Comment by jmcdo29** [comment]
@steinroe I'm getting around to implementing this (it'll be a part of the 2.0 release), and have a question for you that I'd love some input on. With this custom log level, how should the CLI react when it runs into one? Should there be a way to use some sort of config file that maps the custom levels back to the Ogma levels? The levels each have their own color, so if the JSON doesn't have matching values to what the original is (i.e. say that `INFO` becomes `BASIC`) then the CLI wouldn't know to color the `BASIC` log the same way it would an `INFO` log. This could also be problematic if there are multiple levels mapping to the same string.

Should the CLI be strictly for the logs that follow the same format as default (i.e. if custom levels are used the CLI is not guaranteed to behave) or should there be some sort of configuration that allows the CLI to still work?

**Comment by psteinroe** [comment]
That sounds great, thanks for your work! I implemented it across our services in the past days and it works like a charm :)

Mhh I don't use the CLI as of now, but providing the CLI with the same formatting options that the logger is provided with makes the most sense to me. 

Maybe use a similar approach to TypeORM, where the cli reads the configuration from a file. I usually run a small script to write the configuration I provide in the Nest module to a (gitignored) configuration file before using the cli. Although this is not a clean approach, it works well. Maybe we can provide an option to write the formatting options into a file to make that easier. On the other hand, you probably won't use the cli every day, so just manually providing the file with some options might be fine already.

**Comment by psteinroe** [comment]
I just had another idea on how to deal with the config: Write the config directly into the logs as "special" log entry. This way, the cli can just load the config once it sees it and changes in the configs are automatically dealt with.

**Comment by jmcdo29** [comment]
I think I could make some sort of `special` or `originalLevel` property on the JSON work. I'd be concerned about it adding more clutter to the JSON, but usually devs aren't looking at raw JSON anyways, so I don't think it should be too big a deal. Maybe some sort of `ool` (Ogma original level) to keep the key short.

**Comment by psteinroe** [comment]
That sounds reasonable. Let me know if I can support you. 👍

**Comment by jmcdo29** [comment]
`@ogma/logger` 2.0.0 was released yesterday. This is included in functionality of it
