### ISSUE TITLE
[Bug]: the property  WriteStream: createReadStream('info.log') doesn't write on log file

### ISSUE THREAD

**Issue by AyubTouba** [jmcdo29/ogma#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After setting  ` WriteStream: createReadStream('info.log') ` to service configuration for writing logs to the info log file, but it didn't write anything and it doesn't appear any error message 

### Minimum reproduction code

https://github.com/AyubTouba/ogma-bug-writeStream

### Expected behavior

Write logs into log file

### Package(s) version

@ogma/cli: "^2.1.4",
@ogma/nestjs-module: "^3.1.0",
@ogma/platform-express: "^3.0.1",

### Node.js version

12.22.7

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
You should be using `createWriteStream` not `createReadStream`
